### PR TITLE
Permissions and UserGroups needs to be calculated before setting to state

### PR DESCRIPTION
**Pull request by stack72**
without this change, there was a perpetual diff on Usergroups and
permissions

Permissions was returning a default list, but Terraform wasn't allowing
it to be computed. Also permissions when being set needed to be changed
back to the TypeSet rather than jsut a []string

### CODE REVIEW

**Comment by stack72** [comment]
Ping @jbau for thoughts here

**Comment by jbau** [comment]
@stack72 I'm on PTO this week, will take a closer look afterwards.

**Comment by stack72** [comment]
ping... :D

**Comment by keep94** [comment]
stack72,

Thank you for this pull request. Your changes make sense. Can you write a unit test that passes with these changes but fails without these changes?  You fixed multiple mistakes in the code. It would be nice to catch these mistakes with a unit test.

**Comment by stack72** [comment]
Hi @keep94 

I am not going to be able to get to that for quite a while - I will jsut leave this PR open incase someone actually opens an issue that shows the diff here

I have a fork of the repo so will be able to continue with the fork for now

I hope to get to it at some point in the future

If anyone runs the code in master (or latest release) then they will see the diff

Paul

**Comment by keep94** [comment]
Hi stack72,

I was looking at this PR of yours again, and I realized that these changes you made to resource_user could be made to other files as well such as resource_role.  I am happy to take this on, but I was hoping you could give me guidance on testing. Since resource_role doesn't have. your changes yet, what would go wrong with managing roles in terraform?  Once I apply your changes to resource_role, what changes should I notice to how terraform manages roles?  We want to release another version of the wavefront terraform provider, and I am trying to understand whether or not it is worth doing these same changes you did for resource_user.go to the rest of the provider before cutting another release.  Thank you in advance for your help.

**Comment by stack72** [comment]
Hi @keep94 

so the test here would be to write a TF file that creates a user then watch the perpetual diff each time you try and run another apply. Then you can build the new binary from this PR and watch that disappear

Paul

**Pull request merged**
